# Generated by Django 2.1.2 on 2018-10-23 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=7)),
                ('branch', models.CharField(max_length=15)),
                ('paasout_year', models.CharField(max_length=15)),
                ('dob', models.DateTimeField()),
                ('address', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('is_admin', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
